name: kai_inspector
description: A powerful debugging and inspection tool for the Kai Engine, providing real-time visibility into AI chat processing pipelines.
version: 0.0.1
publish_to: 'none'

environment:
  sdk: '^3.4.3'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  kai_engine:
    path: ../kai_engine
  prompt_block: 
    path: ../prompt_block

dev_dependencies:
  flutter_test:
    sdk: flutter
  lints: ^3.0.0
  test: ^1.24.0