name: kai_engine_workspace
repository: https://github.com/pckimlong/kai_engine

# all packages
packages:
  - packages/*

command:
  version:
    branch: main
    linkToCommits: true
    workspaceChangelog: true
    releaseUrl: true

scripts:
  analyze:
    description: Analyze all packages
    run: melos exec --fail-fast -- "if [ \"$MELOS_PACKAGE_NAME\" = \"kai_engine_chat_ui\" ]; then flutter analyze --no-fatal-infos; else dart analyze; fi"

  format:
    description: Format all packages
    run: melos exec -- "dart format --set-exit-if-changed ."

  test:
    description: Run tests for all packages
    run: melos exec --fail-fast -- "if [ \"$MELOS_PACKAGE_NAME\" = \"kai_engine_chat_ui\" ]; then flutter test; else dart test; fi"
    packageFilters:
      dirExists: test

  test:coverage:
    description: Run tests with coverage
    run: melos exec --fail-fast -- "if [ \"$MELOS_PACKAGE_NAME\" = \"kai_engine_chat_ui\" ]; then flutter test --coverage; else dart test; fi"
    packageFilters:
      dirExists: test

  build:runner:
    description: Run build_runner for all packages
    run: melos exec --fail-fast -- "dart run build_runner build --delete-conflicting-outputs"
    packageFilters:
      dependsOn: build_runner
