name: kai_engine_workspace
repository: https://github.com/pckimlong/kai_engine

packages:
  - packages/*

command:
  version:
    branch: main
    linkToCommits: true
    workspaceChangelog: true
    includeCommitId: true
    releaseUrl: true
    hooks:
      preCommit: |
        melos exec -- "dart format CHANGELOG.md 2>/dev/null || true"

  bootstrap:
    usePubspecOverrides: false

scripts:
  analyze:
    description: Analyze all packages
    run: melos exec -- "flutter analyze --no-fatal-infos"

  format:
    description: Format all packages
    run: melos exec -- "dart format --set-exit-if-changed ."

  test:
    description: Run tests for all packages
    run: melos exec --fail-fast -- "flutter test"
    packageFilters:
      dirExists: test

  test:coverage:
    description: Run tests with coverage
    run: melos exec --fail-fast -- "flutter test --coverage"
    packageFilters:
      dirExists: test

  version:dry:
    description: Preview version changes without committing
    run: melos version --yes --no-git-commit-version --no-git-tag-version

  version:
    description: Version packages based on conventional commits
    run: melos version --yes

  list:changed:
    description: List packages that have changed since last release
    run: melos list --diff="HEAD~10" --json

  build:runner:
    description: Run build_runner for all packages
    run: melos exec --fail-fast -- "dart run build_runner build --delete-conflicting-outputs"
    packageFilters:
      dependsOn: build_runner
