name: kai_engine_firebase_ai
description: "A Firebase AI adapter for the Kai Engine."
version: 1.0.0
homepage: https://github.com/pckimlong/kai_engine
repository: https://github.com/pckimlong/kai_engine
issue_tracker: https://github.com/pckimlong/kai_engine/issues
documentation: https://github.com/pckimlong/kai_engine#readme
publish_to: none
resolution: workspace

environment:
  sdk: '^3.9.0-333.2.beta'

dependencies:
  kai_engine:
    path: ../kai_engine
  rxdart: ^0.28.0
  uuid: ^4.5.1
  firebase_ai: ^3.1.0
  freezed_annotation: ^3.1.0
  json_annotation: ^4.9.0
  fast_immutable_collections: ^11.0.4
  synchronized: ^3.4.0
  collection: ^1.19.1
  test: ^1.26.2

dev_dependencies:
  lints: ^2.0.0
  flutter_test:
    sdk: flutter
  build_runner: ^2.6.0
  freezed: ^3.2.0
  json_serializable: ^6.10.0
  mocktail: ^1.0.4