name: Publish to pub.dev

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+*'

jobs:
  publish:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        package: [kai_engine, kai_engine_firebase_ai]
        include:
          - package: kai_engine
            publish: true
          - package: kai_engine_firebase_ai
            publish: false  # Set to true when ready to publish
    steps:
      - uses: actions/checkout@v4
      - uses: dart-lang/setup-dart@v1
        with:
          sdk: stable
      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
      - name: Install dependencies
        run: |
          cd packages/${{ matrix.package }}
          flutter pub get
      - name: Run tests
        run: |
          cd packages/${{ matrix.package }}
          flutter test
      - name: Publish to pub.dev
        if: matrix.publish == true
        uses: k-paxian/dart-package-publisher@v1.5.1
        with:
          accessToken: ${{ secrets.OAUTH_ACCESS_TOKEN }}
          refreshToken: ${{ secrets.OAUTH_REFRESH_TOKEN }}
          skipTests: true
          force: true
          workingDir: packages/${{ matrix.package }}